apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: football

resources:
  - ../../base
  - https://github.com/spinframework/spin-operator/releases/download/v0.6.1/spin-operator.shim-executor.yaml
  - spinapp.yaml

replacements:
  - source:
      kind: Secret
      name: football-app-secret
      fieldPath: stringData.DB_URL
    targets:
      - select:
          kind: SpinApp
          name: football-js-wasm
        fieldPaths:
          - spec.variables.0.value
  - source:
      kind: SpinApp
      name: football-js-wasm
      fieldPath: metadata.name
    targets:
      - select:
          kind: Ingress
          name: football-app
        fieldPaths:
          - spec.rules.0.http.paths.0.backend.service.name

patches:
  - target:
      kind: Ingress
      name: football-app
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/port/number
        value: 80