apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - spinapp.yaml

replacements:
  - source:
      kind: Secret
      name: football-app-secret
      fieldPath: stringData.DB_URL
    targets:
      - select:
          kind: SpinApp
          name: football-js-wasm
        fieldPaths:
          - spec.variables.0.value
