apiVersion: apps/v1
kind: Deployment
metadata:
  name: football-rust-container
spec:
  replicas: 2
  selector:
    matchLabels:
      app: football-rust-container
  template:
    metadata:
      labels:
        app: football-rust-container
    spec:
      containers:
        - name: app
          image: localhost:5000/football-rust-container:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: football-app-secret
                  key: DB_URL
