apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: football

resources:
  - ../../base
  - app-deployment.yaml
  - app-service.yaml

replacements:
  - source:
      kind: Service
      name: football-rust-axum
      fieldPath: metadata.name
    targets:
      - select:
          kind: Ingress
          name: football-app
        fieldPaths:
          - spec.rules.0.http.paths.0.backend.service.name
