apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../wasm-js-baseline

components:
  - ../../components/keda

patches:
  - target:
      kind: SpinApp
      name: football-app
    patch: |-
      - op: add
        path: /spec/enableAutoscaling
        value: true
  - target:
      kind: ScaledObject
      name: football-app-scaler
    patch: |-
      - op: add
        path: /spec/cooldownPeriod
        value: 15