apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kepler-scraper
  namespace: monitoring
  labels:
    release: vmks 
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: kepler 
  endpoints:
  - port: http
    interval: 15s
    scrapeTimeout: 10s
    path: /metrics