daemonset:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi

config:
  monitor:
    interval: 1s
    staleness: 500ms
    maxTerminated: 100
    minTerminatedEnergyThreshold: 0

  exporter:
    prometheus:
      metricsLevel:
        - node
        - pod