apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: football-rust-wasm
spec:
  image: localhost:5000/football-rust-wasm:latest
  executor: containerd-shim-spin
  replicas: 2
  variables:
    - name: db_url
      value: ""
