[package]
name = "teams"
authors = ["exruos <115374714+exruos@users.noreply.github.com>"]
description = ""
version = "0.1.0"
rust-version = "1.95"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.9"
football-shared = { path = "../shared" }
spin-sdk = { version = "5.2.0", optional = true }

[features]
wasm = ["dep:spin-sdk"]
spin-component = ["wasm"]
default = ["spin-component"]
