spin_manifest_version = 2

[application]
name = "football-rust"
version = "0.1.0"
authors = ["exruos <115374714+exruos@users.noreply.github.com>"]
description = "Get football player, team, and match information (monolith)"

[variables]
db_url = { default = "postgres://postgres:postgres@localhost:5438/postgres" }

[[trigger.http]]
route = "/..."
component = "football-rust"

[component.football-rust]
source = "target/wasm32-wasip2/release/football_rust.wasm"
allowed_outbound_hosts = ["postgres://*:5438"]

[component.football-rust.variables]
db_url = "{{ db_url }}"

[component.football-rust.build]
command = "cargo build --target wasm32-wasip2 --release"
workdir = "monolith"
watch = [
  "src/**/*.rs",
  "Cargo.toml",
  "../players/src/**/*.rs",
  "../players/Cargo.toml",
  "../teams/src/**/*.rs",
  "../teams/Cargo.toml",
  "../match/src/**/*.rs",
  "../match/Cargo.toml"
]
