name: football-js

services:
  db:
    platform: linux/amd64
    image: localhost:5000/football-db:postgres-18.4
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5438"
    command: -p 5438
    healthcheck:
      test: "pg_isready -p 5438 -U postgres"
      start_period: "30s"
      start_interval: "1s"
      interval: "24h"

  service:
    build:
      context: ..
      dockerfile: container/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: postgres://postgres:postgres@db:5438/postgres
      PORT: 3000
    ports:
      - "8080:3000"
    restart: unless-stopped