apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: football-app
spec:
  replicas: 1
  image: localhost:5000/football-rust:wasm
  executor: containerd-shim-spin
  resources:
    requests:
      cpu: 500m
      memory: 128Mi
  variables:
    - name: db_url
      value: ""
