apiVersion: v1
kind: Service
metadata:
  name: football-kotlin-container
spec:
  selector:
    app: football-kotlin-container
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
