apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: football

resources:
  - ../wasm-rust-components-baseline

components:
  - ../../components/keda

patches:
  - path: interceptor-patch.yaml
  - path: httproute-patch.yaml
  - target:
      kind: SpinApp
      name: football-app
    patch: |-
      - op: add
        path: /spec/enableAutoscaling
        value: true
      - op: remove
        path: /spec/replicas
  # - target:
  #     kind: ScaledObject
  #     name: football-app-scaler
  #   patch: |-
  #     - op: add
  #       path: /spec/cooldownPeriod
  #       value: 10
