apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: football

resources:
  - ../../base
  - ../../base-deployment

images:
  - name: football-image
    newName: localhost:5000/football-rust
    newTag: axum
