apiVersion: v1
kind: Secret
metadata:
  name: football-app-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
  DB_URL: host=postgres-db-service port=5438 user=postgres password=postgres dbname=postgres
