apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-clean-football
  labels:
    app: spring-clean-football
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-clean-football
  template:
    metadata:
      labels:
        app: spring-clean-football
    spec:
      containers:
      - name: spring-clean-football
        image: registry.gitlab.com/envite-consulting/sustainable-software-architecture/isaqb-green/spring-clean-football-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-db:5438/postgres"
        - name: THC_PATH
          value: "/actuator/health"
        - name: THC_PORT
          value: "8080"
        - name: MATCH_REST_TEAM_NAME_STRATEGY
          value: "POJO_WITHOUT_CACHE"
        - name: MATCH_REST_TEAM_SERVICE_BASE_URL
          value: "http://service:8080"
        - name: SPRING_FLYWAY_ENABLED
          value: "false"
        livenessProbe:
          exec:
            command: ["/workspace/health-check"]
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
